id: jeecgboot-unauth

info:
  name: Jeecg Boot Unauth
  author: SleepingBag945,leadlife
  severity: high
  description: Jeecg Boot 未授权访问
  reference:
    - https://github.com/zan8in/afrog/blob/main/v2/pocs/afrog-pocs/unauthorized/jeecg-boot-unauth.yaml
    - https://github.com/zan8in/afrog/blob/a8161a72649e8ad58321cd481fb3a4e24350e89b/pocs/afrog-pocs/unauthorized/jeecg-boot-unauth.yaml#L4
  tags: jeecgboot,unauth,jeecg
  
http:
  - raw:
      - |
        GET /jeecg-boot/ HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,'Swagger-Bootstrap-UI')
        condition: and

  - raw:
      - |
        GET /jeecg-boot/swagger-resources HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'name','url','swaggerVersion','location')
        condition: and