id: huawei-aolynk-br304-default-password

info:
  name: 华为 Aolynk BR304+ 智能安全路由器默认口令
  author: zan8in
  severity: high
  description: 
  reference: 
    - demo
  classification:
    cve-id: 
  metadata:
    verified: true/false
    fofa-query: Aolynk BR304
  tags: huawei,iot,default-password
  
http:
  - method: GET
    path:
      - "{{BaseURL}}/index_main.html"
    headers:
      Authorization: Basic YWRtaW46YWRtaW4=
    
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,'/menu_admin.html')
        condition: and
