id: sap-netweaver-info-leak

info:
  name: SAP NetWeaver ICM Info page leak
  author: randomstr1ng
  severity: medium
  description: SAP Netweaver是德国思爱普（SAP）公司的一套面向服务的集成化应用平台。该平台主要为SAP应用程序提供开发和运行环境。 SAP NetWeaver 7.4版本的Universal Worklist Configuration中存在信息泄露漏洞。远程攻击者可通过发送特制的HTTP请求利用该漏洞获取敏感的用户信息。
  reference:
    - https://www.acunetix.com/vulnerabilities/web/sap-icf-sap-public-info-sensitive-information-disclosure/
    - https://github.com/Jean-Francois-C/SAP-Security-Audit
  metadata:
    max-request: 1
    shodan-query: http.favicon.hash:-266008933
    repiar: 修改配置文件使目标路径不可访问
  tags: sap,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/sap/public/info"

    matchers:
      - type: regex
        part: body
        regex:
          - "RFC_SYSTEM_INFO.Response"

    extractors:
      - type: regex
        part: body
        regex:
          - "<RFCDEST>.*</RFCDEST>"

# digest: 490a0046304402207ad7d1a61a6958746e27b31d8be46eeffef69a87635db3c0bb23b0ae90fe7f6502207c7a65743f25f94df7cf19bbf362916d654f3887c25795b2063cc9f50ca0d3a9:922c64590222798bb761d5b6d8e72950
